"""add leetcode difficulty stats

Revision ID: 4da4bbf113c2
Revises: 776d9dd0cf1d
Create Date: 2026-09-10 13:45:35.333664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da4bbf113c2'
down_revision = '776d9dd0cf1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('easy_problems', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('medium_problems', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hard_problems', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_stats', schema=None) as batch_op:
        batch_op.drop_column('hard_problems')
        batch_op.drop_column('medium_problems')
        batch_op.drop_column('easy_problems')

    # ### end Alembic commands ###
