"""add phone number and section to users

Revision ID: 762502686dea
Revises: 4da4bbf113c2
Create Date: 2026-09-10 15:48:15.330505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762502686dea'
down_revision = '4da4bbf113c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('section', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('section')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
