"""add college to users

Revision ID: 776d9dd0cf1d
Revises: 117f609017c8
Create Date: 2026-09-09 17:16:18.307245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776d9dd0cf1d'
down_revision = '117f609017c8'
branch_labels = None
depends_on = None


def upgrade():

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'college_id',
                sa.Integer(),
                nullable=True
            )
        )

        batch_op.create_foreign_key(
            'fk_users_college_id',
            'colleges',
            ['college_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('college_id')

    op.drop_table('colleges')
    # ### end Alembic commands ###
