"""create platform stats table

Revision ID: 7d64ab2fa4f8
Revises: 8ce00cbcd3f4
Create Date: 2026-09-08 12:27:00.966706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d64ab2fa4f8'
down_revision = '8ce00cbcd3f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_account_id', sa.Integer(), nullable=False),
    sa.Column('total_submissions', sa.Integer(), nullable=True),
    sa.Column('accepted_submissions', sa.Integer(), nullable=True),
    sa.Column('unique_problems_solved', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('max_rating', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(length=100), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_stats')
    # ### end Alembic commands ###
