"""Add platform account verification fields

Revision ID: 8ce00cbcd3f4
Revises: c92f365bf5b0
Create Date: 2026-09-07 13:51:03.754808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce00cbcd3f4'
down_revision = 'c92f365bf5b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('verification_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_accounts', schema=None) as batch_op:
        batch_op.drop_column('verification_expires_at')
        batch_op.drop_column('verification_code')

    # ### end Alembic commands ###
