"""add verification attempts

Revision ID: ac07347fa960
Revises: 7d64ab2fa4f8
Create Date: 2026-09-08 16:33:46.565357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac07347fa960'
down_revision = '7d64ab2fa4f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_accounts', schema=None) as batch_op:
        batch_op.drop_column('verification_attempts')

    # ### end Alembic commands ###
