"""Add GitHub stats

Revision ID: c986eeac8bd6
Revises: 3fd0ab60ddbc
Create Date: 2026-09-25 17:25:53.414863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c986eeac8bd6'
down_revision = '3fd0ab60ddbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_account_id', sa.Integer(), nullable=False),
    sa.Column('public_repositories', sa.Integer(), nullable=True),
    sa.Column('stars', sa.Integer(), nullable=True),
    sa.Column('forks', sa.Integer(), nullable=True),
    sa.Column('contributions', sa.Integer(), nullable=True),
    sa.Column('commits', sa.Integer(), nullable=True),
    sa.Column('pull_requests', sa.Integer(), nullable=True),
    sa.Column('issues', sa.Integer(), nullable=True),
    sa.Column('repository_count', sa.Integer(), nullable=True),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['platform_account_id'], ['platform_accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_stats')
    # ### end Alembic commands ###
